force-app/main/default/objects/GB_Timeline_Activity__c/GB_Timeline_Activity__c.object-meta.xml
<CustomObject>
    <label>Timeline Activity</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Timeline Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GB_Timeline_Activity__c/fields/createdDate__c.field-meta.xml
<CustomField>
    <fullName>createdDate__c</fullName>
    <description>Created Date</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GB_Timeline_Activity__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <inlineHelpText>Description of activity, displays under title</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GB_Timeline_Activity__c/fields/icon__c.field-meta.xml
<CustomField>
    <fullName>icon__c</fullName>
    <description>The Lightning Design System name of the icon. Names are written in the format &apos;utility:down&apos; where &apos;utility&apos; is the category, and &apos;down&apos; is the specific icon to be displayed.</description>
    <inlineHelpText>The Lightning Design System name of the icon. Names are written in the format &apos;utility:down&apos; where &apos;utility&apos; is the category, and &apos;down&apos; is the specific icon to be displayed.</inlineHelpText>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GB_Timeline_Activity__c/fields/related_to__c.field-meta.xml
<CustomField>
    <fullName>related_to__c</fullName>
    <inlineHelpText>Id of the object to which this activity is related</inlineHelpText>
    <label>Related To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GB_Timeline_Activity__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <inlineHelpText>Title of activity, displays under title</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GB_Timeline_Activity_Controller.cls
public with sharing class GB_Timeline_Activity_Controller {
    @AuraEnabled(cacheable=true scope='global')
    public static GB_Timeline_Activity__c[] getAllTimelineActivities() {
        return [
            SELECT
                Id,
                Name,
                title__c,
                description__c,
                createdDate__c,
                icon__c,
                related_to__c
            FROM GB_Timeline_Activity__c
            WITH SECURITY_ENFORCED
            ORDER BY createdDate__c DESC
            LIMIT 50
        ];
    }
    
    @AuraEnabled(cacheable=true scope='global')
    public static GB_Timeline_Activity__c[] getRelatedTimelineActivities(String relatedToId) {
         // Return all data when no search term
         relatedToId = relatedToId.trim();
         if (relatedToId == '') {
             return null;
         }
       
         // Execute search query
        return [
            SELECT
                Id,
                Name,
                title__c,
                description__c,
                createdDate__c,
                icon__c,
                related_to__c
            FROM GB_Timeline_Activity__c
            WHERE related_to__c = :relatedToId
            WITH SECURITY_ENFORCED
            ORDER BY createdDate__c DESC
            LIMIT 50
        ];
    }
}